micronaut:
  application:
    name: securityJwt
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

micronaut.security.reject-not-found: false
jpa.default.properties.hibernate.hbm2ddl.auto: update

jpa:
  default:
    entity-scan:
      packages: 'com.example.domain'
